global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: node-services
    metrics_path: /metrics
    static_configs:
      - targets:
          - identity-service:3001
          - campaign-service:3002
          - pledge-service:3003
          - payment-service:3004
          - totals-service:3005
